matches:
  - trigger: ":see"
    replace: "🙈"
  - trigger: ":grue"
    replace: |-
      Grüße,
      Janek
  - trigger: ":gree"
    replace: |-
      Best,
      Janek
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
  # Shell commands
  - trigger: ":ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl 'https://api.ipify.org'"
