matches:
  - trigger: ";see"
    replace: "🙈"
  - trigger: ";grue"
    replace: |-
      Grüße,
       Janek
  - trigger: ";gree"
    replace: |-
      Best,
       Janek
  - trigger: ";greg"
    replace: |-
      Greetings from Germany,
       Janek
  - trigger: ";greb"
    replace: |-
      Mit freundlichen Grüßen
       Janek Fischer
     
      ---
      Technischer Leiter https://software-challenge.de, deutscher Programmierwettbewerb für Schüler
      CEO der Polygon GmbH - gesunde IT aus Lichtenfels
      Software Engineering Bachelor @ https://code.berlin
      Privater Blog: https://barelybuggy.blog
  - trigger: ";grer"
    replace: |-
      Greetings from Bavaria,
       Janek
      
      ---
      CTO https://forensicdiscovery.de and https://software-challenge.de
      Software Engineering Student @ https://code.berlin
  - trigger: ";date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
  # Shell commands
  - trigger: ";ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl 'https://api.ipify.org'"
  # Data
  - trigger: ";bic"
    replace: "BYLADEM1001"
  - trigger: ";dkb"
    replace: "Deutsche Kreditbank"
  # Phrases
  - trigger: ";ek"
    replace: "passt :) schauen sie auch gerne noch die anderen Sachen an, wir sortieren grad einiges aus ;)"

